# Tabular Playground - Jan 2021 - Linear Regression

# 1. Librerias a utilizar

In [1]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
input_path = Path('/kaggle/input/tabular-playground-series-jan-2021/')


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

/kaggle/input/tabular-playground-series-jan-2021/sample_submission.csv
/kaggle/input/tabular-playground-series-jan-2021/train.csv
/kaggle/input/tabular-playground-series-jan-2021/test.csv


# 2. Dataset de entrenamiento / Dataset de testing

In [2]:
#Dataset con los datos de entrenamiento

train = pd.read_csv(input_path / 'train.csv', index_col='id')
train.head()

cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
id                                                                         
1   0.670390  0.811300  0.643968  0.291791  0.284117  0.855953  0.890700   
3   0.388053  0.621104  0.686102  0.501149  0.643790  0.449805  0.510824   
4   0.834950  0.227436  0.301584  0.293408  0.606839  0.829175  0.506143   
5   0.820708  0.160155  0.546887  0.726104  0.282444  0.785108  0.752758   
8   0.935278  0.421235  0.303801  0.880214  0.665610  0.830131  0.487113   

       cont8     cont9    cont10    cont11    cont12    cont13    cont14  \
id                                                                         
1   0.285542  0.558245  0.779418  0.921832  0.866772  0.878733  0.305411   
3   0.580748  0.418335  0.432632  0.439872  0.434971  0.369957  0.369484   
4   0.558771  0.587603  0.823312  0.567007  0.677708  0.882938  0.303047   
5   0.823267  0.574466  0.580843  0.769594  0.818143  0.914281  0.279528   
8   0.604157  0.874658  0.863427  0.983575  0.900464  0.935918  0.435772   

      target  
id            
1   7.243043  
3   8.203331  
4   7.776091  
5   6.957716  
8   7.951046

In [3]:
#Dataset con los datos de testing

test = pd.read_csv(input_path / 'test.csv', index_col='id')
train.head()

cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
id                                                                         
1   0.670390  0.811300  0.643968  0.291791  0.284117  0.855953  0.890700   
3   0.388053  0.621104  0.686102  0.501149  0.643790  0.449805  0.510824   
4   0.834950  0.227436  0.301584  0.293408  0.606839  0.829175  0.506143   
5   0.820708  0.160155  0.546887  0.726104  0.282444  0.785108  0.752758   
8   0.935278  0.421235  0.303801  0.880214  0.665610  0.830131  0.487113   

       cont8     cont9    cont10    cont11    cont12    cont13    cont14  \
id                                                                         
1   0.285542  0.558245  0.779418  0.921832  0.866772  0.878733  0.305411   
3   0.580748  0.418335  0.432632  0.439872  0.434971  0.369957  0.369484   
4   0.558771  0.587603  0.823312  0.567007  0.677708  0.882938  0.303047   
5   0.823267  0.574466  0.580843  0.769594  0.818143  0.914281  0.279528   
8   0.604157  0.874658  0.863427  0.983575  0.900464  0.935918  0.435772   

      target  
id            
1   7.243043  
3   8.203331  
4   7.776091  
5   6.957716  
8   7.951046

In [4]:
#Dataset para realizar el submit

submission = pd.read_csv(input_path / 'sample_submission.csv', index_col='id')
display(submission.head())

target
id        
0      0.5
2      0.5
6      0.5
7      0.5
10     0.5

# 3. Split del dataset train

In [5]:
#Selecciono la columna del dataset que tiene la etiqueta del target

target = train['target']
target.head()

id
1    7.243043
3    8.203331
4    7.776091
5    6.957716
8    7.951046
Name: target, dtype: float64

In [6]:
#Realizo la division de train/test
#Elijo una division 75% / 25%

train_clean = train.drop(columns=['target'])
X_train, X_test, y_train, y_test = train_test_split(train_clean, target, train_size=0.75)

In [7]:
X_train.head()

cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
id                                                                             
300113  0.550809  0.682360  0.594540  0.822232  0.572147  0.453934  0.521608   
281450  0.696055  0.733371  0.308971  0.734049  0.463910  0.576128  0.546534   
379237  0.418866  0.150310  0.535078  0.950913  0.412578  0.482361  0.315604   
248819  0.465814  0.792483  0.612441  0.278773  0.284858  0.725248  0.453893   
298674  0.490178  0.359140  0.477646  0.256809  0.279533  0.340415  0.408161   

           cont8     cont9    cont10    cont11    cont12    cont13    cont14  
id                                                                            
300113  0.422623  0.423648  0.561518  0.686326  0.720339  0.365907  0.729646  
281450  0.306611  0.630594  0.814716  0.766426  0.608287  0.809741  0.846508  
379237  0.639880  0.398167  0.468887  0.427632  0.478481  0.293748  0.374103  
248819  0.363110  0.395123  0.450364  0.774635  0.672682  0.626689  0.734072  
298674  0.353454  0.363768  0.440921  0.688862  0.309219  0.675972  0.376075

In [8]:
X_test.head()

cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
id                                                                             
338895  0.496574  0.811647  0.722969  0.331213  0.963961  0.366836  0.471233   
199609  0.648005  0.423015  0.722762  0.218834  0.282657  0.810387  0.813295   
449253  0.409918  0.492220  0.923549  0.200889  0.281190  0.416647  0.779343   
88458   0.350128  0.215989  0.684891  0.752074  0.757716  0.324578  0.249133   
171276  0.636817  0.554259  0.785069  0.558994  0.845442  0.620232  0.579272   

           cont8     cont9    cont10    cont11    cont12    cont13    cont14  
id                                                                            
338895  0.256578  0.422076  0.471754  0.356914  0.298517  0.383677  0.836789  
199609  0.358938  0.487573  0.442211  0.704756  0.803446  0.765154  0.577237  
449253  0.339537  0.361213  0.410170  0.708453  0.705466  0.227069  0.316334  
88458   0.934800  0.580649  0.364642  0.253644  0.345850  0.510993  0.220952  
171276  0.570741  0.319574  0.636608  0.696905  0.747849  0.731386  0.248991

In [9]:
y_train.head()

id
300113    6.796388
281450    9.404765
379237    8.261529
248819    7.508034
298674    8.075130
Name: target, dtype: float64

In [10]:
y_test.head()

id
338895    7.716443
199609    8.531244
449253    8.331279
88458     8.433451
171276    8.444353
Name: target, dtype: float64

# 4. Regresion Lineal

## 4.1 Opcion 1

In [11]:
# Linear Regression

model1 = LinearRegression(fit_intercept=False)

model1.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [12]:
model1.coef_

array([ 1.55404678,  0.15513139,  4.39475895,  1.77789262,  1.59507505,
       -0.25872656,  2.39940893,  0.91281166,  0.41765798, -0.02930671,
       -0.77554564, -0.50427896,  1.79216726,  1.62590261])

In [13]:
y_predicted1 = model1.predict(X_test)

y_predicted1

array([9.2545802 , 8.70710519, 7.80486847, ..., 5.52809138, 8.09812831,
       8.56611614])

In [14]:
score_model1 = mean_squared_error(y_test, y_predicted1, squared=False)

print(f'{score_model1:0.5f}')

1.32966


## 4.2 Opcion 2

# Linear Regression


In [15]:
model2 = LinearRegression(normalize=True)

model2.fit(X_train, y_train)

LinearRegression(normalize=True)

In [16]:
model2.coef_

array([-0.26606516,  0.13224819,  0.07347494,  0.10330807,  0.02267571,
        0.35732245,  0.14305341,  0.05692722,  0.04200554, -0.3976204 ,
        0.12747463,  0.14899719, -0.14345697, -0.01502259])

In [17]:
y_predicted2 = model2.predict(X_test)

y_predicted2

array([7.87151572, 8.04925243, 8.06238009, ..., 7.7974375 , 7.93527825,
       7.98484321])

In [18]:
score_model2 = mean_squared_error(y_test, y_predicted2, squared=False)

print(f'{score_model2:0.5f}')

0.72591


# 5. Generacion del Submit

## 5.1 Opcion 1

In [19]:
submission['target'] = model1.predict(test)

submission.to_csv('linear_regression1.csv')

## 5.2 Opcion 2

In [20]:
submission['target'] = model2.predict(test)

submission.to_csv('linear_regression2.csv')